### ISSUE TITLE
sometimes you can just use JSX

### ISSUE THREAD

**Issue by phil-ho** [gilded-gliders/FEC#21]
https://github.com/gilded-gliders/FEC/blob/d0cc4400b610d7d39df5b381224d44a5d7db3118/client/components/Reviews/rbmessage.jsx#L16-L24

The Message components seems to be divs.  Sometimes you can just use JSX to achieve the same results and not have to deal with dependencies. For example, the code below functions exactly the same way except now its easier to read and doesn't require you to import anything or use conditionals.

```js
<div style = {summary}>{summary}</div>
<br></br>
<div style = {body}>{i.body}</div>
<br></br>
<div style = {body}>{i.recommend}</div>
<br></br>
<Photo photo = { i.photos } />
<br></br>
<div style = {response}>Response: <br></br> { res }</div>
<br></br>
```

PS - you can use CSS to achieve what you're using `<br>` for, further simplifying your code

```js
<div style = {summary}>{summary}</div>
<div style = {body}>{i.body}</div>
<div style = {body}>{i.recommend}</div>
<Photo photo = { i.photos } />
<div style = {response}>Response: <br></br> { res }</div>

//...
const summary = {
  fontSize: '12px',
  fontWeight: 'bold'
  margin-bottom: 1em; // use any unit of spacing you want to create the affect of <br>
}
```

**Comment by kennethwang1028** [comment]
I will keep message component first, because I use massage component other where else, also I am waiting for soo to finish her parts, so we can have same style, now all styles is mini work to look smaller to example only, later I will move all my style to one file and try to mini my style's  amount. a lot of them are same.  I will keep this advise in mind.
